# action.yml
name: 'Testkube CLI'
description: 'Install Testkube and execute Testkube command'
inputs:
  testkube-version:
    description: 'Testkube version to install'
    required: false
    default: '1.11.19'
runs:
  using: 'node16'
  main: 'index.js'

    
