# action.yml
name: 'Testkube'
description: 'Execute Testkube command'
inputs:
  command:
    description: 'Command'
    required: true
    default: 'get'
  resource:
    description: 'Resource'
    required: false
    default: 'tests'
  namespace:
    description: 'Namespace'
    required: false
    default: 'testkube'
  api-key:
    description: 'API key'
    required: false
    default: ''
  api-uri:
    description: 'API uri'
    required: false
    default: ''
  parameters:
    description: 'Parameters'
    required: false
    default: ''
  stdin:
    description: 'Standard input'
    required: false
    default: ''
outputs:
  result:
    description: 'The result of the command'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
    - ${{ inputs.resource }}
    - ${{ inputs.namespace }}
    - ${{ inputs.api-key }}
    - ${{ inputs.api-uri }}
    - ${{ inputs.parameters }}
    - ${{ inputs.stdin }}
